# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""Adapters that LOAD ground-truth artifacts — THE EXTRACTION SEAM.

Every check reads artifacts through a function here, never via a hardcoded path.
When the Sentinel is extracted to a shared `vortex-contracts` repo, only this
module changes; core/ and checks/ move untouched.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import ssl
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

# contracts/sentinel/core/sources.py -> repo root is parents[3].
REPO_ROOT = Path(__file__).resolve().parents[3]
FRONTEND = REPO_ROOT / "frontend"
BACKEND = REPO_ROOT / "backend"
BASELINE_DIR = REPO_ROOT / "contracts" / "baseline"

CATALOG_MANIFEST = FRONTEND / "src" / "lib" / "catalog.manifest.json"
BACKEND_CATALOG_TYPES = BACKEND / "app" / "data" / "catalog_types.json"
GEN_CATALOG_TS = FRONTEND / "scripts" / "gen-catalog.ts"
CATALOG_GENERATED_TS = FRONTEND / "src" / "lib" / "catalog.generated.ts"
SCHEMA_DIR = FRONTEND / "schema"
MAKEFILE = REPO_ROOT / "Makefile"
COMPOSE = REPO_ROOT / "docker" / "docker-compose.yml"
MAIN_PY = BACKEND / "app" / "main.py"


# ── file helpers ──────────────────────────────────────────────────────────────
def sha256_file(path: Path) -> str | None:
    if not path.exists():
        return None
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


# ── catalog (frontend) ────────────────────────────────────────────────────────
def load_catalog_manifest() -> dict:
    """The committed merged-catalog manifest (types the picker offers + input
    hashes). Generated by frontend/scripts/gen-catalog-manifest.ts."""
    return json.loads(read_text(CATALOG_MANIFEST))


def catalog_kinds(manifest: dict | None = None) -> dict[str, set[str]]:
    """Picker-offered types split by kind (frontend source of truth)."""
    m = manifest or load_catalog_manifest()
    return {"sources": set(m.get("sources", [])), "sinks": set(m.get("sinks", []))}


def load_backend_types() -> dict[str, set[str]]:
    """The backend's accepted component types, kind-aware. Generated from the same
    Vector schema as the catalog (backend/app/data/catalog_types.json), so it
    should equal `catalog_kinds()` — C1 guards that."""
    data = json.loads(read_text(BACKEND_CATALOG_TYPES))
    return {
        "sources": set(data.get("sources", [])),
        "sinks": set(data.get("sinks", [])),
    }


# ── backend app imports (lazy — only the app-touching checks pay for these) ───
def _ensure_backend_on_path() -> None:
    # Append (not insert-at-0) so backend modules can't shadow stdlib/site packages.
    p = str(BACKEND)
    if p not in sys.path:
        sys.path.append(p)


def load_model_columns() -> dict[str, set[str]]:
    """{table: {columns}} from SQLAlchemy `Base.metadata`.

    models/__init__.py only registers a subset, so import every model module to
    fully populate the metadata (matches what main.py's import graph does before
    `create_all`)."""
    _ensure_backend_on_path()
    import importlib

    import app.models as models_pkg  # type: ignore

    pkgdir = Path(models_pkg.__file__).parent
    for mod in pkgdir.glob("*.py"):
        if mod.stem != "__init__":
            importlib.import_module(f"app.models.{mod.stem}")
    from app.core.database import Base  # type: ignore

    return {
        name: {c.name for c in table.columns}
        for name, table in Base.metadata.tables.items()
    }


# ── DB provisioning (parse the raw SQL in _run_schema_upgrades) ───────────────
_ALTER_RE = re.compile(
    r"ALTER\s+TABLE\s+(\w+)\s+ADD\s+COLUMN\s+IF\s+NOT\s+EXISTS\s+(\w+)",
    re.IGNORECASE,
)


def load_upgrade_alters() -> set[tuple[str, str]]:
    """{(table, column)} that `_run_schema_upgrades()` adds via ALTER. Existing
    DBs only gain new columns through these (create_all won't touch live tables)."""
    return set(_ALTER_RE.findall(read_text(MAIN_PY)))


# ── version pins (A0) ─────────────────────────────────────────────────────────
def load_pins() -> dict[str, list[str] | str | None]:
    """Every place the Vector version is pinned. The leader image is a *runtime*
    pin (allowed to differ); the rest must agree."""
    pins: dict[str, list[str] | str | None] = {}

    mk = re.search(
        r"^VECTOR_VERSION\s*\??=\s*([0-9][^\s#]*)", read_text(MAKEFILE), re.M
    )
    pins["Makefile:VECTOR_VERSION"] = mk.group(1) if mk else None

    gc = re.search(
        r"VECTOR_SCHEMA_VERSION\s*\|\|\s*'([^']+)'", read_text(GEN_CATALOG_TS)
    )
    pins["gen-catalog.ts:default"] = gc.group(1) if gc else None

    # GENERATED_SCHEMA_VERSION sits near the top of a very large file.
    head = CATALOG_GENERATED_TS.read_text(encoding="utf-8")[:4000]
    gv = re.search(r"GENERATED_SCHEMA_VERSION\s*=\s*'([^']+)'", head)
    pins["catalog.generated.ts:GENERATED_SCHEMA_VERSION"] = gv.group(1) if gv else None

    schema_versions = sorted(
        m.group(1)
        for p in SCHEMA_DIR.glob("vector-*-schema.json")
        if (m := re.match(r"vector-(.+)-schema\.json$", p.name))
    )
    pins["schema/*.json"] = schema_versions

    leader = (
        sorted(
            set(
                re.findall(r"timberio/vector:([0-9][^-\s]*)-alpine", read_text(COMPOSE))
            )
        )
        if COMPOSE.exists()
        else []
    )
    pins["docker-compose leader (runtime, exempt)"] = leader

    return pins


# ── baseline (C2) ─────────────────────────────────────────────────────────────
def baseline_path(version: str) -> Path:
    return BASELINE_DIR / f"columns-{version}.json"


def load_baseline(version: str) -> dict[str, list[str]] | None:
    path = baseline_path(version)
    if not path.exists():
        return None
    return json.loads(read_text(path))


def write_baseline(version: str, columns: dict[str, set[str]]) -> Path:
    BASELINE_DIR.mkdir(parents=True, exist_ok=True)
    payload = {t: sorted(cols) for t, cols in sorted(columns.items())}
    path = baseline_path(version)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return path


# ── pinned version + committed schema (A2/A3) ─────────────────────────────────
def pinned_version() -> str | None:
    """The canonical Vector version pin (Makefile:VECTOR_VERSION)."""
    pins = load_pins()
    v = pins.get("Makefile:VECTOR_VERSION")
    return v if isinstance(v, str) else None


def committed_schema_path(version: str) -> Path:
    return SCHEMA_DIR / f"vector-{version}-schema.json"


def load_committed_schema(version: str) -> bytes | None:
    path = committed_schema_path(version)
    return path.read_bytes() if path.exists() else None


# ── docker (A2) ───────────────────────────────────────────────────────────────
def docker_available() -> bool:
    if not shutil.which("docker"):
        return False
    try:
        subprocess.run(
            ["docker", "info"],
            capture_output=True,
            timeout=15,
            check=False,
        )
        return True
    except (OSError, subprocess.SubprocessError):
        return False


def fetch_vector_schema_via_docker(version: str) -> bytes | None:
    """Dump the component schema from the real, pinned Vector image — exactly what
    `make catalog` does. Returns None if docker is unavailable or the run fails."""
    if not docker_available():
        return None
    image = f"timberio/vector:{version}-alpine"
    try:
        proc = subprocess.run(
            ["docker", "run", "--rm", image, "generate-schema"],
            capture_output=True,
            timeout=180,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if proc.returncode != 0 or not proc.stdout:
        return None
    return proc.stdout


# ── latest release (A3) ───────────────────────────────────────────────────────
_STABLE_TAG_RE = re.compile(r"^v?(\d+\.\d+\.\d+)$")


def _github_json(url: str, timeout: float) -> object | None:
    # GitHub's API returns 403 without a User-Agent — set one or A3 falsely "skips".
    req = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "vortexflow-sentinel",
        },
    )
    # Use certifi's CA bundle when present so verification works on machines whose
    # Python lacks system certs (common on macOS); falls back to the default context.
    try:
        import certifi

        ctx = ssl.create_default_context(cafile=certifi.where())
    except Exception:  # noqa: BLE001 — best effort; default context otherwise
        ctx = None
    try:
        with urllib.request.urlopen(req, timeout=timeout, context=ctx) as resp:  # noqa: S310 (https)
            return json.loads(resp.read())
    except (urllib.error.URLError, OSError, ValueError, TimeoutError):
        return None


def fetch_latest_vector_release(timeout: float = 8.0) -> str | None:
    """Highest STABLE Vector release (e.g. '0.50.0'), or None if offline / lookup
    fails. Vector marks odd `dev-*` tags as GitHub's "latest", so we pull the list
    and take the max `vX.Y.Z` among non-prerelease, non-draft releases."""
    data = _github_json(
        "https://api.github.com/repos/vectordotdev/vector/releases?per_page=100",
        timeout,
    )
    if not isinstance(data, list):
        return None
    versions: list[str] = []
    for rel in data:
        if not isinstance(rel, dict) or rel.get("prerelease") or rel.get("draft"):
            continue
        m = _STABLE_TAG_RE.match(str(rel.get("tag_name", "")))
        if m:
            versions.append(m.group(1))
    if not versions:
        return None
    return max(versions, key=version_tuple)


def version_tuple(v: str) -> tuple[int, ...]:
    """Parse a dotted version into an int tuple for comparison (best-effort)."""
    parts: list[int] = []
    for chunk in v.lstrip("v").split("."):
        m = re.match(r"\d+", chunk)
        parts.append(int(m.group()) if m else 0)
    return tuple(parts)
