// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

/*
 * gen-catalog.ts — regenerate the bundled fallback catalog (catalog.generated.ts)
 * from a Vector JSON schema, using the SAME converter the app uses at runtime
 * (src/lib/catalogGen). Single source of truth — no drift between build + runtime.
 *
 * Run: pnpm gen:catalog   (or `make catalog [VECTOR_VERSION=x.y.z]`, which also
 * fetches the schema for that version).
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { schemaToCatalog } from '../src/lib/catalogGen'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const SCHEMA_VERSION = process.env.VECTOR_SCHEMA_VERSION || '0.56.0'
const SCHEMA_PATH = path.join(
  __dirname,
  '..',
  'schema',
  `vector-${SCHEMA_VERSION}-schema.json`,
)
const OUT_PATH = path.join(__dirname, '..', 'src', 'lib', 'catalog.generated.ts')

const schema = JSON.parse(fs.readFileSync(SCHEMA_PATH, 'utf8'))
const { sources, sinks } = schemaToCatalog(schema)
const serialize = (c: unknown) => JSON.stringify(c, null, 2)

const out = `// AUTO-GENERATED by scripts/gen-catalog.ts from schema/vector-${SCHEMA_VERSION}-schema.json
// DO NOT EDIT BY HAND. Run \`make catalog\` (or \`pnpm gen:catalog\`) to regenerate.
//
// One CatalogComponent per Vector source/sink component type, with
// generated: true. Curated entries in catalog.ts WIN on type collision.
/* eslint-disable */
import type { CatalogComponent } from './catalog'

export const GENERATED_SCHEMA_VERSION = '${SCHEMA_VERSION}'

export const GENERATED_SOURCES: CatalogComponent[] = ${serialize(sources)}

export const GENERATED_SINKS: CatalogComponent[] = ${serialize(sinks)}
`

fs.writeFileSync(OUT_PATH, out)
console.log(`Wrote src/lib/catalog.generated.ts`)
console.log(`  sources: ${sources.length}`)
console.log(`  sinks:   ${sinks.length}`)
